spring.application.name=users

server.port=8082
spring.datasource.url=jdbc:mariadb://localhost:3306/squaregames_users
spring.datasource.username=squaregames_users
spring.datasource.password=squaregames_users
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update